CREATE TABLE DONORSINFO(
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100),
	CONTACTNUMBER VARCHAR(14) NOT NULL UNIQUE,
	ADDRESS VARCHAR(255),
	BLOODGROUP VARCHAR(4)
)
	